# Name: Ofek Malul
# Date: 6/1/2023

name: Java CI with Maven

on:
  push:
    branches: ["master"]

env:
  IMAGE_VERSION: 1.0.0
  DOCKER_REPO_NAME: "ofekmalul/java_hello_world"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Create a docker image and versioning by date + commit hash first 6 chars
        run: export IMAGE_VERSION=$(date +%Y%m%d)-$(echo $GITHUB_SHA | cut -c1-6)
      - name: Build docker image
        run: docker build . -t java-hello-world:$IMAGE_VERSION

  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWD
      - name: Tag image to DockerHub
        run: docker tag java-hello-world:$IMAGE_VERSION $DOCKER_REPO_NAME:1.0.0
      - name: Push to DockerHub
        run: docker push ${{secrets.DOCKER_USER}}/ofekmalul/java_hello_world:1.0.0
