# Name: Ofek Malul
# Date: 6/1/2023

name: Java CI with Maven

on:
  push:
    branches: ["master"]

env:
  IMAGE_VERSION_SEMANTIC: 1.0.0
  DOCKER_REPO_NAME: "ofekmalul/java_hello_world"

jobs:
  # CI_Java_Project:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Set up JDK 17
  #       uses: actions/setup-java@v3
  #       with:
  #         java-version: "17"
  #         distribution: "temurin"
  #         cache: maven
  #     - name: Build and Test with Maven
  #       run: mvn package

  #     - name: Create a docker image and versioning by date + commit hash first 6 chars
  #       run: |
  #         IMAGE_VERSION=$(date +%Y-%m-%d)-$(echo $GITHUB_SHA | cut -c1-6)
  #         echo "IMAGE_VERSION=$IMAGE_VERSION" >> $GITHUB_ENV

  #     - name: Build docker image
  #       run: |
  #         docker build . --tag ${DOCKER_REPO_NAME}:$IMAGE_VERSION

  #     - name: docker login
  #       env:
  #         DOCKER_USER: ${{secrets.DOCKER_USER}}
  #         DOCKER_PASSWD: ${{secrets.DOCKER_PASSWORD}}
  #       run: docker login -u $DOCKER_USER -p $DOCKER_PASSWD

  #     - name: push to DockerHub
  #       run: docker push ${{secrets.DOCKER_USER}}/java_hello_world:${IMAGE_VERSION}

  CD_Java_Project:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Deploy to EC2
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          HOST_IP: ${{ secrets.IP_ADDRESS_JAVA_INSTANCE }}
          PRIVATE_KEY: ${{ secrets.SSH_KEY_INSTANACE }}

        run: |
          ssh -o StrictHostKeyChecking=no -i ${PRIVATE_KEY} ${USER_NAME}@${HOST_IP}
          sudo docker run ofekmalul/java_hello_world:latest

  # CD_Java_Project:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: hashicorp/setup-terraform@v3

  #     - name: initilize
  #       run: cd terraform && terraform init

  #     - name: plan
  #       run: cd terraform && terraform plan -no-color

  #     - name: apply
  #       run: cd terraform && terraform apply -auto-approve

  # update_semantic_version:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - users: actions/checkout@v3
  #     - name: Bump version and push tag
  #       uses: remorses/bump-version@js
  #       with:
  #         version_file: ./version.txt
  #       name: build docker image with semantic versioning
  #       run : docker build . -t java-hello-world:$
